version: '3.3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
      PG_TABLE_WIND: "${PG_TABLE_WIND}"
      PG_TABLE_USERS: "${PG_TABLE_USERS}"
    networks:
      - backend

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  web:
    build: simulator/.
    depends_on:
      - db
    restart: always
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DB: "${PG_DB}"
      PG_TABLE_WIND: "${PG_TABLE_WIND}"
    ports:
      - "3000:3000"
    networks:
      - backend

  web-server:
    build: web-server/.
    depends_on:
      - db
    restart: always
    volumes:
      - "./web-server:/usr/src/m7011e_web_server"
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DB: "${PG_DB}"
      PG_TABLE_USERS: "${PG_TABLE_USERS}"
    ports:
      - "3100:3100"
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
    driver: bridge
