version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "~/m7011e/db/data:/var/lib/postgresql/data"
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: WIND_SIM
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
