version: '3.3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      CLIMATE_PASSWORD: "${CLIMATE_PASSWORD}"
      ELECTRICITY_GRID_PASSWORD: "${ELECTRICITY_GRID_PASSWORD}"
    networks:
      - backend

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  web:
    build: simulator/.
    depends_on:
      - db
    restart: always
    volumes:
      - "./simulator:/usr/src/m7011e_sim"
      - "/usr/src/m7011e_sim/node_modules/"
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      CLIMATE_PASSWORD: "${CLIMATE_PASSWORD}"
      ELECTRICITY_GRID_PASSWORD: "${ELECTRICITY_GRID_PASSWORD}"
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - backend

  web-server:
    build: web-server/.
    depends_on:
      - db
    restart: always
    volumes:
      - "./web-server:/usr/src/m7011e_web_server"
      - "/usr/src/m7011e_web_server/node_modules/"
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      ELECTRICITY_GRID_PASSWORD: "${ELECTRICITY_GRID_PASSWORD}"
      WS_PRIVATE_KEY: "${WS_PRIVATE_KEY}"
      WS_SESSION_SECRET: "${WS_SESSION_SECRET}"
    ports:
      - "3100:3100"
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
    driver: bridge
