version: '3.3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "~/m7011e/db/data:/var/lib/postgresql/data"
      - "./simulator/db:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
      PG_TABLE_WIND: "${PG_TABLE_WIND}"
    networks:
      - backend

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  web:
    build: simulator/.
    depends_on:
      - db
    restart: always
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DB: "${PG_DB}"
      PG_TABLE_WIND: "${PG_TABLE_WIND}"
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
