version: '3.3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./db/setup.sh:/docker-entrypoint-initdb.d/setup.sh"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      CLIMATE_PASSWORD: "${CLIMATE_PASSWORD}"
      ELECTRICITY_GRID_PASSWORD: "${ELECTRICITY_GRID_PASSWORD}"
    networks:
      - backend

  simulator:
    build:
      context: simulator/.
      args:
        develop: "false"
    depends_on:
      - db
    restart: always
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      CLIMATE_PASSWORD: "${CLIMATE_PASSWORD}"
      ELECTRICITY_GRID_PASSWORD: "${ELECTRICITY_GRID_PASSWORD}"
      WS_PRIVATE_KEY: "${WS_PRIVATE_KEY}"
    ports:
      - "3000:3000"
    networks:
      - backend

  web:
    build:
      context: web-server/.
      args:
        develop: "false"
    depends_on:
      - db
    restart: always
    environment:
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      ELECTRICITY_GRID_PASSWORD: "${ELECTRICITY_GRID_PASSWORD}"
      WS_PRIVATE_KEY: "${WS_PRIVATE_KEY}"
      WS_SESSION_SECRET: "${WS_SESSION_SECRET}"
      WEB_SERVER_PORT: "80"
    ports:
      - "80:80"
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
    driver: bridge
