#!/bin/bash
set -e

POSTGRES="psql -d ${POSTGRES_DB} -a -U${POSTGRES_USER}"

$POSTGRES <<EOSQL
CREATE TABLE ${PG_TABLE_WIND}(
   time TIMESTAMP NOT NULL PRIMARY KEY,
   windSpeed REAL NOT NULL,
   unit VARCHAR NOT NULL
);
EOSQL
